#spring.application.name=server
spring:
  application:
    name: server
  profiles:
    default: local

server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
      force-request: true
      force-response: true

jwt:
  expiration: 3600000
  refresh-expiration: 2592000000

