-- 1. 신규 컬럼 추가 (데이터 유지하며 필드만 생성)
ALTER TABLE users
    ADD COLUMN IF NOT EXISTS status VARCHAR (20) DEFAULT 'NORMAL',
    ADD COLUMN IF NOT EXISTS user_type VARCHAR (25) NOT NULL DEFAULT 'USER',
    ADD COLUMN IF NOT EXISTS count_interests INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS level VARCHAR (20) NOT NULL DEFAULT 'BEGINNER',
    ADD COLUMN IF NOT EXISTS sign_up_complete TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS notification_status TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS point INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS exp INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS count_read_content INT NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS character_level VARCHAR (20) NOT NULL DEFAULT 'LEVEL_1',
    ADD COLUMN IF NOT EXISTS last_read_date DATE,
    ADD COLUMN IF NOT EXISTS last_login_at DATETIME(6),
    ADD COLUMN IF NOT EXISTS created_at DATETIME(6),
    ADD COLUMN IF NOT EXISTS updated_at DATETIME(6);

-- 2. 기존 컬럼 속성 변경 (로그에서 Hibernate가 시도했던 작업들을 명시)
-- 이미 해당 타입이라도 다시 실행해도 무방합니다.
ALTER TABLE users MODIFY COLUMN email VARCHAR (50);
ALTER TABLE users MODIFY COLUMN user_type VARCHAR (25) NOT NULL;

ALTER TABLE users
    ADD UNIQUE INDEX IF NOT EXISTS uk_user_email (email);
